
package ar.gov.afip.wsaa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginCMSService", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", wsdlLocation = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms?WSDL")
public class LoginCMSService
    extends Service
{

    private final static URL LOGINCMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINCMSSERVICE_EXCEPTION;
    private final static QName LOGINCMSSERVICE_QNAME = new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://wsaahomo.afip.gov.ar/ws/services/LoginCms?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINCMSSERVICE_WSDL_LOCATION = url;
        LOGINCMSSERVICE_EXCEPTION = e;
    }

    public LoginCMSService() {
        super(__getWsdlLocation(), LOGINCMSSERVICE_QNAME);
    }

    public LoginCMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINCMSSERVICE_QNAME, features);
    }

    public LoginCMSService(URL wsdlLocation) {
        super(wsdlLocation, LOGINCMSSERVICE_QNAME);
    }

    public LoginCMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINCMSSERVICE_QNAME, features);
    }

    public LoginCMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginCMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginCMSPortType
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMSPortType getLoginCms() {
        return super.getPort(new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCms"), LoginCMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginCMSPortType
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMSPortType getLoginCms(WebServiceFeature... features) {
        return super.getPort(new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCms"), LoginCMSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINCMSSERVICE_EXCEPTION!= null) {
            throw LOGINCMSSERVICE_EXCEPTION;
        }
        return LOGINCMSSERVICE_WSDL_LOCATION;
    }

}
