
package ar.gov.afip.wsaa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginCMS", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginCMSPortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     * @throws LoginFault_Exception
     */
    @WebMethod
    @WebResult(name = "loginCmsReturn", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
    @RequestWrapper(localName = "loginCms", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "ar.gov.afip.wsaa.LoginCms")
    @ResponseWrapper(localName = "loginCmsResponse", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "ar.gov.afip.wsaa.LoginCmsResponse")
    public String loginCms(
        @WebParam(name = "in0", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
        String in0)
        throws LoginFault_Exception
    ;

}
